<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>MetalForth Language. By Mark Flamer</string>
	<key>fileTypes</key>
	<array>
		<string>mfs</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?i)^\s*(Public|Private)?\s*(Class|Function|Sub|Property)\s*([a-zA-Z_]\w*)\s*(\(.*\)\s*)?$</string>
	<key>foldingStopMarker</key>
	<string>(?i)^\s*End (Class|Function|Sub|Property)\s*$</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>MetalForth</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.control.metalforth</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*((?i:\:))\s*([a-zA-Z_]\w*)</string>
			<key>name</key>
			<string>meta.function.nimrod</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nimrod</string>
				</dict>
			</dict>
			<key>match</key>
			<string>#.*$\n?</string>
			<key>name</key>
			<string>comment.line.apostrophe.nimrod</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.nimrod</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(REM ).*$\n?</string>
			<key>name</key>
			<string>comment.line.rem.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(block|break|case|continue|discard|do|elif|else|end|except|for|from|if|method|type|proc|return|when|while|with|without|import|var|let|const|template|macro|generic|using|iterator|converter)\b</string>
			<key>name</key>
			<string>keyword.control.nimrod</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>pragma.source.nimrod</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>pragma.source.nimrod</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>pragma.source.nimrod</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((([\(]{1})+([.]{1}))([a-z]+[a-zA-Z0-9_]*)(([.]{1})+([}]{1})))</string>
			<key>name</key>
			<string>comment.control.metalforth</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[\(\)\{\}]</string>
			<key>name</key>
			<string>parentheses.source.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[`]</string>
			<key>name</key>
			<string>ticks.source.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[|.,!@#$%^&amp;*&lt;&gt;:?~=/\-\+\[\]]</string>
			<key>name</key>
			<string>operator.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|or|not|xor|shl|shr|div|mod|in|notin|is|isnot|of)\b</string>
			<key>name</key>
			<string>operator.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(addr|atomic|const|enum|export|ptr|ref|static|tuple|object|var|mixin|typedesc|distinct|array)\b</string>
			<key>name</key>
			<string>storage.type.nimrod</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.source.nimrod</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>operator.source.nimrod</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([A-Z]+[a-zA-Z0-9_]*)([\:,+ \']*)</string>
			<key>name</key>
			<string>meta.type.source.nimrod</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.nimrod</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>parentheses.source.Nimrod</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-z]+[a-zA-Z0-9_]*)([\(]{1})</string>
			<key>name</key>
			<string>meta.function.source.nimrod</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.nimrod</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>parentheses.source.Nimrod</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([a-z]+[a-zA-Z0-9_]*)([\[]{1})</string>
			<key>name</key>
			<string>meta.function.source.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(([0-9][0-9_]*)|([0-9][0-9_]*(u|u8|u16|u32|u64))|([0-9][0-9_]*(i|i8|i16|i32|i64)))\b</string>
			<key>name</key>
			<string>constant.numeric.integer.source.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0x[a-fA-F0-9_]+)|(0x[a-fA-F0-9_]+(u|u8|u16|u32|u64))|(0x[a-fA-F0-9_]+(i|i8|i16|i32|i64)))\b</string>
			<key>name</key>
			<string>constant.numeric.hex.source.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0b[01_]+)|(0b[01_]+(u|u8|u16|u32|u64))|(0b[01_]+(i|i8|i16|i32|i64)))\b</string>
			<key>name</key>
			<string>constant.numeric.binary.source.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>([0-9][0-9_]*(f32|f64|f))|([0-9][0-9_]*([eE][+-]=[0-9_]+))|([0-9][0-9_]*([eE][+-]=[0-9_]+)(f32|f64|f))|([0-9][0-9_]*\.[0-9_]+)|([0-9][0-9_]*\.[0-9_]+(f32|f64|f))|([0-9][0-9_]*\.[0-9_]+%([eE][+-]=[0-9_]+))|([0-9][0-9_]*\.[0-9_]+%([eE][+-]=[0-9_]+)(f32|f64|f))</string>
			<key>name</key>
			<string>constant.numeric.float.source.nimrod</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(nil)\b)</string>
			<key>name</key>
			<string>constant.language.nimrod</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.nimrod</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"(?!")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.nimrod</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.nimrod</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>""</string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.nimrod</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nimrod</string>
	<key>uuid</key>
	<string>4060da00-dca1-11e1-9b23-0800200c9a66</string>
</dict>
</plist>
